version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: chatgpt-discord-bot
    container_name: chatgpt-discord-bot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    network_mode: "host"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    network_mode: "host"